//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corbis.Web.UI.Checkout {
    
    
    public partial class InvalidPaymentMethod {
        
        /// <summary>
        /// paymentAlertTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize paymentAlertTitle;
        
        /// <summary>
        /// paymentAlertMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize paymentAlertMessage;
        
        /// <summary>
        /// btnApplyForCredit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.GlassButton btnApplyForCredit;
        
        /// <summary>
        /// btnContactCorbis control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.GlassButton btnContactCorbis;
        
        /// <summary>
        /// quit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize quit;
    }
}
