//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per Contract.
        /// </summary>
        internal static string AsPerContract {
            get {
                return ResourceManager.GetString("AsPerContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American Express.
        /// </summary>
        internal static string A_card {
            get {
                return ResourceManager.GetString("A_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST &amp; Prov.Sales Tax (if appl.).
        /// </summary>
        internal static string Canada_Tax {
            get {
                return ResourceManager.GetString("Canada_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only standard western European characters, numeric values, and punctuation characters such as &apos;@&apos; and &apos;.&apos; are allowed..
        /// </summary>
        internal static string ContainsNonAsciiCharacters {
            get {
                return ResourceManager.GetString("ContainsNonAsciiCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - - - - -.
        /// </summary>
        internal static string Dashes {
            get {
                return ResourceManager.GetString("Dashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eurocard.
        /// </summary>
        internal static string E_card {
            get {
                return ResourceManager.GetString("E_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT:.
        /// </summary>
        internal static string French_Tax {
            get {
                return ResourceManager.GetString("French_Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JCB.
        /// </summary>
        internal static string J_card {
            get {
                return ResourceManager.GetString("J_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your personal information contains nonstandard Western European characters. Please fix these before attempting to change your billing country..
        /// </summary>
        internal static string MemberDataContainsNonAsciiCharacters {
            get {
                return ResourceManager.GetString("MemberDataContainsNonAsciiCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mastercard.
        /// </summary>
        internal static string M_card {
            get {
                return ResourceManager.GetString("M_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (optional).
        /// </summary>
        internal static string Optional {
            get {
                return ResourceManager.GetString("Optional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not released.
        /// </summary>
        internal static string Order_ModelNoRelease {
            get {
                return ResourceManager.GetString("Order_ModelNoRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        internal static string Order_ModelRelease {
            get {
                return ResourceManager.GetString("Order_ModelRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not released.
        /// </summary>
        internal static string Order_PropertyNoRelease {
            get {
                return ResourceManager.GetString("Order_PropertyNoRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Released.
        /// </summary>
        internal static string Order_PropertyRelease {
            get {
                return ResourceManager.GetString("Order_PropertyRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price now.
        /// </summary>
        internal static string priceNow {
            get {
                return ResourceManager.GetString("priceNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (required).
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RF.
        /// </summary>
        internal static string RFText {
            get {
                return ResourceManager.GetString("RFText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RM.
        /// </summary>
        internal static string RMText {
            get {
                return ResourceManager.GetString("RMText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RS.
        /// </summary>
        internal static string RSText {
            get {
                return ResourceManager.GetString("RSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one.
        /// </summary>
        internal static string SelectOne {
            get {
                return ResourceManager.GetString("SelectOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has timed out.We apologize for the inconvenience..
        /// </summary>
        internal static string sessionTimeoutMessage {
            get {
                return ResourceManager.GetString("sessionTimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session time-out.
        /// </summary>
        internal static string sessionTimeoutTitle {
            get {
                return ResourceManager.GetString("sessionTimeoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For Credit.
        /// </summary>
        internal static string SiteMap_ApplyForCreditDescription {
            get {
                return ResourceManager.GetString("SiteMap_ApplyForCreditDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply For Credit.
        /// </summary>
        internal static string SiteMap_ApplyForCreditPageTitle {
            get {
                return ResourceManager.GetString("SiteMap_ApplyForCreditPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string SiteMap_HomePageDescription {
            get {
                return ResourceManager.GetString("SiteMap_HomePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string SiteMap_HomePageTitle {
            get {
                return ResourceManager.GetString("SiteMap_HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string SiteMap_MyAccountPageDescription {
            get {
                return ResourceManager.GetString("SiteMap_MyAccountPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        internal static string SiteMap_MyAccountPageTitle {
            get {
                return ResourceManager.GetString("SiteMap_MyAccountPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightboxes.
        /// </summary>
        internal static string SiteMap_MyLightboxesPageDescription {
            get {
                return ResourceManager.GetString("SiteMap_MyLightboxesPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lightboxes.
        /// </summary>
        internal static string SiteMap_MyLightboxesPageTitle {
            get {
                return ResourceManager.GetString("SiteMap_MyLightboxesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string SiteMap_MyOrderHistoryPageDescription {
            get {
                return ResourceManager.GetString("SiteMap_MyOrderHistoryPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        internal static string SiteMap_MyOrderHistoryPageTitle {
            get {
                return ResourceManager.GetString("SiteMap_MyOrderHistoryPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile &amp; Preferences.
        /// </summary>
        internal static string SiteMap_MyProfilePageDescription {
            get {
                return ResourceManager.GetString("SiteMap_MyProfilePageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile &amp; Preferences.
        /// </summary>
        internal static string SiteMap_MyProfilePageTitle {
            get {
                return ResourceManager.GetString("SiteMap_MyProfilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be Determined.
        /// </summary>
        internal static string Tax_Unknown {
            get {
                return ResourceManager.GetString("Tax_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISA.
        /// </summary>
        internal static string V_card {
            get {
                return ResourceManager.GetString("V_card", resourceCulture);
            }
        }
    }
}
