//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corbis.Web.UI.Accounts {
    
    
    public partial class ChangePersonalInformation {
        
        /// <summary>
        /// title control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize title;
        
        /// <summary>
        /// closePersonalInfoPopupImage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Image closePersonalInfoPopupImage;
        
        /// <summary>
        /// vHub control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.ValidationHub vHub;
        
        /// <summary>
        /// usernameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize usernameLabel;
        
        /// <summary>
        /// username control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox username;
        
        /// <summary>
        /// name1Label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize name1Label;
        
        /// <summary>
        /// name1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox name1;
        
        /// <summary>
        /// name2Label control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize name2Label;
        
        /// <summary>
        /// name2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox name2;
        
        /// <summary>
        /// furiganaLastNameRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow furiganaLastNameRow;
        
        /// <summary>
        /// furiganaLastNameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize furiganaLastNameLabel;
        
        /// <summary>
        /// furiganaLastName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox furiganaLastName;
        
        /// <summary>
        /// furiganaFirstNameRow control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow furiganaFirstNameRow;
        
        /// <summary>
        /// furiganaFirstNameLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize furiganaFirstNameLabel;
        
        /// <summary>
        /// furiganaFirstName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox furiganaFirstName;
        
        /// <summary>
        /// emailLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize emailLabel;
        
        /// <summary>
        /// email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox email;
        
        /// <summary>
        /// confirmEmailLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize confirmEmailLabel;
        
        /// <summary>
        /// confirmEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox confirmEmail;
        
        /// <summary>
        /// securityQuestionLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize securityQuestionLabel;
        
        /// <summary>
        /// securityQuestion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.DropDownList securityQuestion;
        
        /// <summary>
        /// answerLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize answerLabel;
        
        /// <summary>
        /// securityAnswer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.TextBox securityAnswer;
        
        /// <summary>
        /// mailingAddressPersonalInfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize mailingAddressPersonalInfo;
        
        /// <summary>
        /// mailingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Address mailingAddress;
        
        /// <summary>
        /// lb control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.LinkButton lb;
        
        /// <summary>
        /// changePersonalInfoSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.GlassButton changePersonalInfoSave;
        
        /// <summary>
        /// changePersonalInfoCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.GlassButton changePersonalInfoCancel;
        
        /// <summary>
        /// validatorContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder validatorContainer;
    }
}
