//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Corbis.Web.UI.Accounts {
    
    
    public partial class EditMailingAddress {
        
        /// <summary>
        /// editMailingAddressTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize editMailingAddressTitle;
        
        /// <summary>
        /// addMailingAddressTitle control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Localize addMailingAddressTitle;
        
        /// <summary>
        /// editMailingAddressPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel editMailingAddressPanel;
        
        /// <summary>
        /// editMailingAddressValidationSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.ValidationGroupSummary editMailingAddressValidationSummary;
        
        /// <summary>
        /// nonAsciiValidator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CustomValidator nonAsciiValidator;
        
        /// <summary>
        /// sameAsBusiness control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.ImageCheckbox sameAsBusiness;
        
        /// <summary>
        /// mailingAddressControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.Address mailingAddressControl;
        
        /// <summary>
        /// editMailingAddressSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.GlassButton editMailingAddressSave;
        
        /// <summary>
        /// editMailingAddressCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Corbis.Web.UI.Controls.GlassButton editMailingAddressCancel;
        
        /// <summary>
        /// validatorContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder validatorContainer;
    }
}
