//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "9.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Legal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Legal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Legal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///                            &lt;p&gt;
        ///                                PLEASE READ THIS CAREFULLY. THE FOLLOWING TERMS AND CONDITIONS CONSTITUTE
        ///                                    A BINDING AGREEMENT BETWEEN YOU AND CORBIS CORPORATION (&quot;Corbis&quot;). By
        ///                                    using the Corbis beta web site (&quot;Site&quot;) and/or downloading any content,
        ///                                    you are agreeing to participate in the evaluation of a beta (pre-release)
        ///                                    version [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BetaSiteUsageAgreementText {
            get {
                return ResourceManager.GetString("BetaSiteUsageAgreementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BETA SITE USAGE AGREEMENT.
        /// </summary>
        internal static string BetaSiteUsageAgreementTitle {
            get {
                return ResourceManager.GetString("BetaSiteUsageAgreementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2001-{YEAR} by Corbis Corporation. All visual media © by Corbis Corporation and/or its media providers. All Rights Reserved..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       &lt;p&gt;&lt;b&gt;Anschrift:&lt;/b&gt;&lt;br /&gt;Corbis GmbH&lt;br /&gt;Kaistra&amp;#223;e 2&lt;br /&gt;40221 D&amp;#252;sseldorf&lt;br /&gt; &lt;/p&gt;&lt;p&gt;&lt;br/&gt;&lt;b&gt;Kontakt:&lt;/b&gt;&lt;br /&gt;&lt;a class=RegularLink href=&quot;mailto:service.germany@corbis.com&quot; target=_blank&gt;service.germany@corbis.com&lt;/a&gt; &lt;br /&gt;Tel.: +49 (0)211 912 82-0&lt;br /&gt;Fax:   +49 (0)211 912 82-34&lt;br /&gt;&lt;/p&gt;&lt;p&gt;E-Mail: F&amp;#252;r den einfachen und schnellen Kontakt nutzen Sie bitte unsere &lt;a class=&quot;RegularLink&quot; href=&quot;/CustomerService/CustomerService.aspx&quot; target=_top&gt;Kontaktseite&lt;/a&gt;.&lt;/p&gt;&lt;p&gt;&lt;br/&gt;&lt;b&gt;Sitz de [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImprintText {
            get {
                return ResourceManager.GetString("ImprintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string ImprintTitle {
            get {
                return ResourceManager.GetString("ImprintTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Last Updated on 04/22/2008&lt;/b&gt;&lt;br /&gt;
        ///        &lt;p /&gt;
        ///        At Corbis, we understand and respect your concern about the privacy of any information 
        ///        you supply while at our web site. We believe that knowledge is the key to monitoring 
        ///        and protecting how your information is used on the Internet. This statement sets forth 
        ///        our Privacy Policy and describes the practice we follow with respect to all 
        ///        visitors to this web site, which is owned and operated by Corbis Corporat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivacyPolicyText {
            get {
                return ResourceManager.GetString("PrivacyPolicyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE READ THIS CAREFULLY.  THE FOLLOWING TERMS AND CONDITIONS CONSTITUTE A BINDING AGREEMENT 
        ///    BETWEEN YOU AND CORBIS HOLDINGS, INC., PARENT COMPANY OF CORBIS CORPORATION (“Corbis”).  By using 
        ///    the Corbis web site (“Site”) and/or downloading any content or activating your account on the 
        ///    Community Pages (as defined below), you agree to be bound by and comply with this Site Usage Agreement (“Agreement”).  
        ///    If you do not wish to be bound by this Agreement, do not use this Site.&lt;p /&gt;
        ///THIS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SiteUsageAgreementText {
            get {
                return ResourceManager.GetString("SiteUsageAgreementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Usage Agreement.
        /// </summary>
        internal static string SiteUsageAgreementTitle {
            get {
                return ResourceManager.GetString("SiteUsageAgreementTitle", resourceCulture);
            }
        }
    }
}
